title: DC4822
description: >- # this means to ignore newlines until "baseurl:"
  Warsaw DEFCON Group
url: "https://dc4822.org"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postcss-v2

postcss:
  cache: false

future: true
